from pathlib import Path

path = Path('index.html')
text = path.read_text(encoding='utf-8')
marker = "// ==========================\n// ESTADO\nfunction updateStatus() {\n"
insert = "// ==========================\n// VIDEO PRODUCTOS\nconst videoModal = document.getElementById('videoModal');\nconst videoFrame = document.getElementById('videoFrame');\nconst videoPlayer = document.getElementById('videoPlayer');\nconst videoSource = document.getElementById('videoSource');\nconst videoUnavailable = document.getElementById('videoUnavailable');\n\nfunction openVideoModal(src) {\n    if (!src || !videoModal) return;\n\n    videoFrame.classList.add('hidden');\n    videoPlayer.classList.add('hidden');\n    videoUnavailable.classList.add('hidden');\n\n    if (src.includes('youtube.com') || src.includes('youtu.be')) {\n        videoFrame.src = normalizeYouTubeEmbed(src);\n        videoFrame.classList.remove('hidden');\n    } else {\n        videoSource.src = src;\n        videoPlayer.load();\n        videoPlayer.classList.remove('hidden');\n    }\n\n    videoModal.classList.remove('hidden');\n}\n\nfunction normalizeYouTubeEmbed(src) {\n    if (src.includes('youtube.com/embed/')) {\n        return src + (src.includes('?') ? '&' : '?') + 'autoplay=1';\n    }\n\n    if (src.includes('watch?v=')) {\n        return src.replace('watch?v=', 'embed/') + '?autoplay=1';\n    }\n\n    if (src.includes('youtu.be/')) {\n        const_id = src.split('youtu.be/').pop().split(/[?&]/)[0];\n        return f'https://www.youtube.com/embed/{const_id}?autoplay=1';\n    }\n\n    return src;\n}\n\nfunction closeVideoModal() {\n    if (!videoModal) return;\n\n    videoFrame.src = '';\n    if (videoPlayer) {\n        videoPlayer.pause();\n        videoPlayer.currentTime = 0;\n    }\n\n    videoModal.classList.add('hidden');\n}\n\nfunction attachProductVideoListeners() {\n    const videoCards = document.querySelectorAll('.product-card[data-video]');\n\n    videoCards.forEach(card => {\n        const src = card.dataset.video;\n\n        card.addEventListener('click', () => openVideoModal(src));\n        card.addEventListener('keydown', event => {\n            if (event.key === 'Enter' || event.key === ' ') {\n                event.preventDefault();\n                openVideoModal(src);\n            }\n        });\n    });\n}\n\ninsert_text = insert + marker
if marker not in text:
    raise SystemExit('marker not found')
text = text.replace(marker, insert_text, 1)
path.write_text(text, encoding='utf-8')
print('inserted')
